= Tornium

A third party, general-purpose website and Discord bot dedicated to simplifying the playing of https://www.torn.com[Torn City].

== Features
- Faction banking
- OD detection
- Discord-based retaliation notifications
- Discord-based OC ready and delay notifications
- Discord-based stakeouts
- Discord-based user verification
- Discord-based stock verification
- Stat database
- Chain list generator

== Installation
Not yet supported.

=== Optional packages
Tornium can be run without all of the below optional packages, but will auto-detect installation and run with those packages if they are installed.

 - ddtrace - for monitoring of the flask and celery instances
 - orjson - for increased performance in encoding and decoding of JSON in all API calls

== License
https://github.com/dssecret/tornium-pro/blob/master/LICENSE[AGPLv3]

== Release Notes
This project follows https://semver.org/[semver v2.0] so all bug fixes, breaking changes, features, etc. can be found in the https://github.com/dssecret/tornium-pro/blob/master/CHANGELOG.adoc[changelog].

== Contact
- tiksan on Discord at tiksan(hastag)9110
- tiksan on Torn at https://www.torn.com/profiles.php?XID=2383326[tiksan [2383326\]]