= Tornium

A third party, general-purpose website and Discord bot dedicated to simplifying the playing of https://www.torn.com[Torn City].

Tornium is split into three main repositories:

 - https://www.github.com/Tornium/tornium-core[tornium-core] - Flask app for frontend and Discord bot
 - https://www.github.com/Tornium/tornium-celery[tornium-celery] - Celery app containing Celery tasks and configuration
 - https://www.github.com/Tornium/tornium-commons[tornium-commons] - common utility functions and classes for Tornium

== Features
 - Faction banking
 - OD detection
 - Discord-based retaliation notifications
 - Discord-based OC ready and delay notifications
 - Discord-based stakeouts
 - Discord-based user verification
 - Discord-based stock verification
 - Stat database
 - Chain list generator

== Deprecation Notice
IMPORTANT: Pre-existing stakeouts will be removed in the v0.4.x release cycle. Pre-existing stakeouts will not be migrated.
IMPORTANT: Assist request forwarding options will be removed in the v0.5.x release cycle.

== Installation
Not yet supported.

=== Optional packages
Tornium can be run without all of the below optional packages, but will auto-detect installation and run with those packages if they are installed.

 - ddtrace - for monitoring of the flask and celery instances
 - orjson - for increased performance in encoding and decoding of JSON in all API calls

== Tornium Extensions
Tornium partially supports extensions for new Discord commands and new Flask endpoints (with no support for Celery tasks currently). However, over-writing pre-existing commands and endpoints is not supported. A template for Tornium extensions can be found at https://github.com/dssecret/tornium-extension-template[dssecret/tornium-extension-template]. Extensions automatically install into Tornium upon start up of Tornium with auto-detection of extensions (must start with `tornium-`). For more information or if you find any issues, please open an issue in either repository.

NOTE: Tornium extensions must be released as open source code under a GPLv3 or another GPL license due to the restrictions of the https://github.com/dssecret/tornium-pro/blob/master/LICENSE[tornium-pro license]. For more details, take a look at https://www.gnu.org/licenses/gpl-3.0.en.html[GPL website].

== License
https://github.com/dssecret/tornium-pro/blob/master/LICENSE[AGPLv3]

== Release Notes
This project follows https://semver.org/[semver v2.0] so all bug fixes, breaking changes, features, etc. can be found in the https://github.com/dssecret/tornium-pro/blob/master/CHANGELOG.adoc[changelog].

== Contributing to Tornium
All commits must be signed with a `Signed-off-by` line in the commit description matching the commit author. This certifies (under the Developer Certificate of Origin) that you have written the code or have the right to submit the code to the project. Full details can be found https://developercertificate.org/[here].

== Donations
Donations are accepted with both real life money and in-game money. However, due to restrictions with
Torn's RMT rules, donors using real life money should NOT expect anything (e.g. additional features,
support, etc.) from their contributions. Contributions with real life money will go towards
server costs (and other hosting costs).

Donate https://www.buymeacoffee.com/tornium[here]!

== Contact
 - tiksan on Discord at tiksan(hastag)9110
 - tiksan on Torn at https://www.torn.com/profiles.php?XID=2383326[tiksan [2383326\]]