# This file has been autogenerated by tornium-commons (rds_lua_hasher).
# Do NOT modify this file as it may be upgraded in the next commit.
#
# Copyright (C) 2021-2023 tiksan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BHASH = "687c15b58be056b05ff8ce46c192c8a25d753152"
BHASH_CALL = "e539776d120146fa3a483d6156b539a27f5d0b31"
