postgres:
    password: ENC[AES256_GCM,data:l8YDFRBYlBY=,iv:G4kiFAwTzLI5tiEd7Y9owp24E35DDKYKg7YN+CHcyRc=,tag:AwA/LOIZs5stcjY+NyVZaQ==,type:str]
    replicator_password: ENC[AES256_GCM,data:EW4uNyAhfbIBAQ9DaPXEiHlOu10=,iv:PH4aWCnBt+UKWAetuTMziLuo99UQY9UOwMfiAe3jZ5A=,tag:YzpcFQeFmKZmMCLlH0Qvrw==,type:str]
    admin_password: ENC[AES256_GCM,data:m4ge0dRnW4T5IzTJ94pBeOOuWD8=,iv:AAijYuiepcRxQ+0ONGCIjAMkQ9VMzZHl8gMpwv66xLk=,tag:d8AT9C+KG4JxArrLnB1enA==,type:str]
pgbackrest:
    aes_encryption_key: ENC[AES256_GCM,data:M6lRAKQqGWregH99IFa8FNfeV7DoswGqlBziSkJsrzv+IkLhE3YX50SH9yTLhBZNPYwndOsXDrNk9xuy/ov08w==,iv:Oc/G9A5hQi4GpQ/VYxt4x7iRhHJs30oSN+lND8pU/bg=,tag:RN/COgfS9+UJf4buPt4AEA==,type:str]
    backblaze_key_id: ENC[AES256_GCM,data:zclZkkiTTKpYYHMJstqMSKg9pailhM4e/A==,iv:00BmGOyGXXAi4rXTaRKOCnO9dw9dMIc+LtANIg1zDtE=,tag:FMJOUoWtyo9YXZGRd9fjxg==,type:str]
    backblaze_key: ENC[AES256_GCM,data:0+ltpFaZloDpN7GzfNZ52XkbyCCdby9beoaGeLphvw==,iv:WeHxmB1z3w1ECnu+RLBeamdlxQSoRf1QQbedsumd5SY=,tag:9QVnNj/ySYlf/ghB4ZXgwA==,type:str]
sops:
    age:
        - recipient: age1fgjd4dltc5kdf3784azfgc60a8ca2k7rfl2tfe2pqa82c806tq9s9l73w8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L24vc252MHhBaHd0a3ZV
            VXM5YmlTREZ6MmFUdzU2bURmWkxPNHErczFrCk1Dd09TaWp2UnU3dDc5M055ZzM5
            VHVtMTZST2doYkE4VFhUWjhBWVNlZFUKLS0tIHJYWmU4QkNaenhsZlc1Qll0REs3
            bmRTZDZPRTV2ejh1ZjRieUtJYTJEdjAK65ehn1FOrCMY5/t8+/5qoLUhm8zCNJRg
            hsLSqO0Lf208RcsF+Bsrd2hOnS+LuLqn11zTO3KFb1IF+LejWGGbgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vzxu44cax0zn8k3ymvuxnpe75wyt7xhqw95vr9l6y6j9lr5seasqmpm086
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SHhxM2E4Q0JRZlV6c0Jq
            VjYvdkZrVDd1WUJ2WjBkbUU0VkErMWdXbVQ0Ci9sZXd3KzZoalJ1NE1iRTlzVDNv
            VXI0VVVPandkOUkrM0lzVDFNRHB3UXcKLS0tIHBJQS9hMElIQVY4QkhOVk9EVWNZ
            aWpSbHRWREJFdE9rSlE5eEpNeVIrTUEKRtcNNlux92nw+S2YY5r3G8r8dMgfLiKM
            rqtNrO3GdPXQQi0p2R/1clYSIWlnqbCF06FoNXGXDvuxkTvTaWSNhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T19:32:19Z"
    mac: ENC[AES256_GCM,data:1htv5IouW+W04cMfKPYtep7Tw+lHBG7WA8glWo/53Iz50Mwm1ew0s1SleRe0lkel6ddwXgU9SNZBSIYWdhQP/S6DpqIgYHSYhoileNazET81UTi1DTiU2wQ5snLyaOdQV98ZepcMFkTntob4NzvVWem2cNRXs7/8Cw0d8p+3FeA=,iv:2neJ3TOFfnOID6C+vPmcL9s1FdMow5wrQQOamdy8YHE=,tag:N+gsOEzEzJeOg5bC2gRmVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
