[trigger]
uuid = "989ad601-12a7-4ca9-8d61-52c932b7707d"
name = "Faction Members Traveling"
description = "This notification will show who in a faction is traveling and when they will land.\n\nModify the TRAVEL_METHOD parameter to change the travel method used in the landing time calculations (1 = standard; 2 = airstrip; 3 = WLT; 4 = BCT)"
owner = 2383326

[implementation]
cron = "* * * * *"
resource = "faction"
selections = ["basic"]
message_type = "update"

[implementation.parameters]
TRAVEL_METHOD = "(integer) method of travel used"
