# Copyright (C) 2021-2025 tiksan
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule Tornium.Schema.PersonalStats do
  use Ecto.Schema

  @type t :: %__MODULE__{
          user_id: pos_integer(),
          user: Tornium.Schema.User.t(),
          timestamp: Date.t(),
          useractivity: integer(),
          activestreak: integer(),
          bestactivestreak: integer(),
          itemsbought: integer(),
          pointsbought: integer(),
          itemsboughtabroad: integer(),
          weaponsbought: integer(),
          itemssent: integer(),
          auctionswon: integer(),
          auctionsells: integer(),
          attackswon: integer(),
          attackslost: integer(),
          attacksdraw: integer(),
          bestkillstreak: integer(),
          moneymugged: integer(),
          attacksstealthed: integer(),
          attackhits: integer(),
          attackmisses: integer(),
          attackdamage: integer(),
          attackcriticalhits: integer(),
          respectforfaction: integer(),
          onehitkills: integer(),
          defendswon: integer(),
          defendslost: integer(),
          defendsstalemated: integer(),
          bestdamage: integer(),
          roundsfired: integer(),
          yourunaway: integer(),
          theyrunaway: integer(),
          highestbeaten: integer(),
          peoplebusted: integer(),
          failedbusts: integer(),
          peoplebought: integer(),
          peopleboughtspent: integer(),
          virusescoded: integer(),
          cityfinds: integer(),
          traveltimes: integer(),
          bountiesplaced: integer(),
          bountiesreceived: integer(),
          bountiescollected: integer(),
          totalbountyreward: integer(),
          revives: integer(),
          revivesreceived: integer(),
          medicalitemsused: integer(),
          statenhancersused: integer(),
          trainsreceived: integer(),
          totalbountyspent: integer(),
          drugsused: integer(),
          overdosed: integer(),
          meritsbought: integer(),
          personalsplaced: integer(),
          classifiedadsplaced: integer(),
          mailssent: integer(),
          friendmailssent: integer(),
          factionmailssent: integer(),
          companymailssent: integer(),
          spousemailssent: integer(),
          largestmug: integer(),
          cantaken: integer(),
          exttaken: integer(),
          kettaken: integer(),
          lsdtaken: integer(),
          opitaken: integer(),
          shrtaken: integer(),
          spetaken: integer(),
          pcptaken: integer(),
          xantaken: integer(),
          victaken: integer(),
          chahits: integer(),
          heahits: integer(),
          axehits: integer(),
          grehits: integer(),
          machits: integer(),
          pishits: integer(),
          rifhits: integer(),
          shohits: integer(),
          smghits: integer(),
          piehits: integer(),
          slahits: integer(),
          argtravel: integer(),
          mextravel: integer(),
          dubtravel: integer(),
          hawtravel: integer(),
          japtravel: integer(),
          lontravel: integer(),
          soutravel: integer(),
          switravel: integer(),
          chitravel: integer(),
          cantravel: integer(),
          dumpfinds: integer(),
          dumpsearches: integer(),
          itemsdumped: integer(),
          daysbeendonator: integer(),
          caytravel: integer(),
          jailed: integer(),
          hospital: integer(),
          attacksassisted: integer(),
          bloodwithdrawn: integer(),
          networth: integer(),
          missionscompleted: integer(),
          contractscompleted: integer(),
          dukecontractscompleted: integer(),
          missioncreditsearned: integer(),
          consumablesused: integer(),
          candyused: integer(),
          alcoholused: integer(),
          energydrinkused: integer(),
          nerverefills: integer(),
          unarmoredwon: integer(),
          h2hhits: integer(),
          organisedcrimes: integer(),
          territorytime: integer(),
          territoryjoins: integer(),
          arrestsmade: integer(),
          booksread: integer(),
          traveltime: integer(),
          boostersused: integer(),
          rehabs: integer(),
          rehabcost: integer(),
          awards: integer(),
          receivedbountyvalue: integer(),
          racingskill: integer(),
          raceswon: integer(),
          racesentered: integer(),
          racingpointsearned: integer(),
          specialammoused: integer(),
          cityitemsbought: integer(),
          hollowammoused: integer(),
          tracerammoused: integer(),
          piercingammoused: integer(),
          incendiaryammoused: integer(),
          attackswonabroad: integer(),
          defendslostabroad: integer(),
          rankedwarringwins: integer(),
          retals: integer(),
          elo: integer(),
          jobpointsused: integer(),
          reviveskill: integer(),
          itemslooted: integer(),
          rankedwarhits: integer(),
          raidhits: integer(),
          territoryclears: integer(),
          refills: integer()
        }

  @primary_key false
  schema "personalstats" do
    belongs_to(:user, Tornium.Schema.User, references: :tid)
    field(:timestamp, :date)

    field(:useractivity, :integer)
    field(:activestreak, :integer)
    field(:bestactivestreak, :integer)
    field(:itemsbought, :integer)
    field(:pointsbought, :integer)
    field(:itemsboughtabroad, :integer)
    field(:weaponsbought, :integer)
    field(:itemssent, :integer)
    field(:auctionswon, :integer)
    field(:auctionsells, :integer)
    field(:attackswon, :integer)
    field(:attackslost, :integer)
    field(:attacksdraw, :integer)
    field(:bestkillstreak, :integer)
    field(:moneymugged, :integer)
    field(:attacksstealthed, :integer)
    field(:attackhits, :integer)
    field(:attackmisses, :integer)
    field(:attackdamage, :integer)
    field(:attackcriticalhits, :integer)
    field(:respectforfaction, :integer)
    field(:onehitkills, :integer)
    field(:defendswon, :integer)
    field(:defendslost, :integer)
    field(:defendsstalemated, :integer)
    field(:bestdamage, :integer)
    field(:roundsfired, :integer)
    field(:yourunaway, :integer)
    field(:theyrunaway, :integer)
    field(:highestbeaten, :integer)
    field(:peoplebusted, :integer)
    field(:failedbusts, :integer)
    field(:peoplebought, :integer)
    field(:peopleboughtspent, :integer)
    field(:virusescoded, :integer)
    field(:cityfinds, :integer)
    field(:traveltimes, :integer)
    field(:bountiesplaced, :integer)
    field(:bountiesreceived, :integer)
    field(:bountiescollected, :integer)
    field(:totalbountyreward, :integer)
    field(:revives, :integer)
    field(:revivesreceived, :integer)
    field(:medicalitemsused, :integer)
    field(:statenhancersused, :integer)
    field(:trainsreceived, :integer)
    field(:totalbountyspent, :integer)
    field(:drugsused, :integer)
    field(:overdosed, :integer)
    field(:meritsbought, :integer)
    field(:personalsplaced, :integer)
    field(:classifiedadsplaced, :integer)
    field(:mailssent, :integer)
    field(:friendmailssent, :integer)
    field(:factionmailssent, :integer)
    field(:companymailssent, :integer)
    field(:spousemailssent, :integer)
    field(:largestmug, :integer)
    field(:cantaken, :integer)
    field(:exttaken, :integer)
    field(:kettaken, :integer)
    field(:lsdtaken, :integer)
    field(:opitaken, :integer)
    field(:shrtaken, :integer)
    field(:spetaken, :integer)
    field(:pcptaken, :integer)
    field(:xantaken, :integer)
    field(:victaken, :integer)
    field(:chahits, :integer)
    field(:heahits, :integer)
    field(:axehits, :integer)
    field(:grehits, :integer)
    field(:machits, :integer)
    field(:pishits, :integer)
    field(:rifhits, :integer)
    field(:shohits, :integer)
    field(:smghits, :integer)
    field(:piehits, :integer)
    field(:slahits, :integer)
    field(:argtravel, :integer)
    field(:mextravel, :integer)
    field(:dubtravel, :integer)
    field(:hawtravel, :integer)
    field(:japtravel, :integer)
    field(:lontravel, :integer)
    field(:soutravel, :integer)
    field(:switravel, :integer)
    field(:chitravel, :integer)
    field(:cantravel, :integer)
    field(:dumpfinds, :integer)
    field(:dumpsearches, :integer)
    field(:itemsdumped, :integer)
    field(:daysbeendonator, :integer)
    field(:caytravel, :integer)
    field(:jailed, :integer)
    field(:hospital, :integer)
    field(:attacksassisted, :integer)
    field(:bloodwithdrawn, :integer)
    field(:networth, :integer)
    field(:missionscompleted, :integer)
    field(:contractscompleted, :integer)
    field(:dukecontractscompleted, :integer)
    field(:missioncreditsearned, :integer)
    field(:consumablesused, :integer)
    field(:candyused, :integer)
    field(:alcoholused, :integer)
    field(:energydrinkused, :integer)
    field(:nerverefills, :integer)
    field(:unarmoredwon, :integer)
    field(:h2hhits, :integer)
    field(:organisedcrimes, :integer)
    field(:territorytime, :integer)
    field(:territoryjoins, :integer)
    field(:arrestsmade, :integer)
    field(:booksread, :integer)
    field(:traveltime, :integer)
    field(:boostersused, :integer)
    field(:rehabs, :integer)
    field(:rehabcost, :integer)
    field(:awards, :integer)
    field(:receivedbountyvalue, :integer)
    field(:racingskill, :integer)
    field(:raceswon, :integer)
    field(:racesentered, :integer)
    field(:racingpointsearned, :integer)
    field(:specialammoused, :integer)
    field(:cityitemsbought, :integer)
    field(:hollowammoused, :integer)
    field(:tracerammoused, :integer)
    field(:piercingammoused, :integer)
    field(:incendiaryammoused, :integer)
    field(:attackswonabroad, :integer)
    field(:defendslostabroad, :integer)
    field(:rankedwarringwins, :integer)
    field(:retals, :integer)
    field(:elo, :integer)
    field(:jobpointsused, :integer)
    field(:reviveskill, :integer)
    field(:itemslooted, :integer)
    field(:rankedwarhits, :integer)
    field(:raidhits, :integer)
    field(:territoryclears, :integer)
    field(:refills, :integer)
  end
end
