# Copyright (C) 2021-2023 tiksan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from peewee import BigIntegerField, DateTimeField, IntegerField

from .base_model import BaseModel


class PersonalStats(BaseModel):
    #### pstat_id ####
    # tid = bin(tid << 8)
    # timestamp = bin(timestamp)
    # pstat_id = int(tid, 2) + int(timestamp, 2)
    ##################

    pstat_id = BigIntegerField(primary_key=True)
    tid = IntegerField()
    timestamp = DateTimeField()

    # Uses jsonb as size of values is not known beyond "int"
    useractivity = BigIntegerField(null=True)
    activestreak = BigIntegerField(null=True)
    bestactivestreak = BigIntegerField(null=True)
    itemsbought = BigIntegerField(null=True)
    pointsbought = BigIntegerField(null=True)
    itemsboughtabroad = BigIntegerField(null=True)
    weaponsbought = BigIntegerField(null=True)
    itemssent = BigIntegerField(null=True)
    auctionswon = BigIntegerField(null=True)
    auctionsells = BigIntegerField(null=True)
    attackswon = BigIntegerField(null=True)
    attackslost = BigIntegerField(null=True)
    attacksdraw = BigIntegerField(null=True)
    bestkillstreak = BigIntegerField(null=True)
    moneymugged = BigIntegerField(null=True)
    attacksstealthed = BigIntegerField(null=True)
    attackhits = BigIntegerField(null=True)
    attackmisses = BigIntegerField(null=True)
    attackdamage = BigIntegerField(null=True)
    attackcriticalhits = BigIntegerField(null=True)
    respectforfaction = BigIntegerField(null=True)
    onehitkills = BigIntegerField(null=True)
    defendswon = BigIntegerField(null=True)
    defendslost = BigIntegerField(null=True)
    defendsstalemated = BigIntegerField(null=True)
    bestdamage = BigIntegerField(null=True)
    roundsfired = BigIntegerField(null=True)
    yourunaway = BigIntegerField(null=True)
    theyrunaway = BigIntegerField(null=True)
    highestbeaten = BigIntegerField(null=True)
    peoplebusted = BigIntegerField(null=True)
    failedbusts = BigIntegerField(null=True)
    peoplebought = BigIntegerField(null=True)
    peopleboughtspent = BigIntegerField(null=True)
    virusescoded = BigIntegerField(null=True)
    cityfinds = BigIntegerField(null=True)
    traveltimes = BigIntegerField(null=True)
    bountiesplaced = BigIntegerField(null=True)
    bountiesreceived = BigIntegerField(null=True)
    bountiescollected = BigIntegerField(null=True)
    totalbountyreward = BigIntegerField(null=True)
    revives = BigIntegerField(null=True)
    revivesreceived = BigIntegerField(null=True)
    medicalitemsused = BigIntegerField(null=True)
    statenhancersused = BigIntegerField(null=True)
    trainsreceived = BigIntegerField(null=True)
    totalbountyspent = BigIntegerField(null=True)
    drugsused = BigIntegerField(null=True)
    overdosed = BigIntegerField(null=True)
    meritsbought = BigIntegerField(null=True)
    personalsplaced = BigIntegerField(null=True)
    classifiedadsplaced = BigIntegerField(null=True)
    mailssent = BigIntegerField(null=True)
    friendmailssent = BigIntegerField(null=True)
    factionmailssent = BigIntegerField(null=True)
    companymailssent = BigIntegerField(null=True)
    spousemailssent = BigIntegerField(null=True)
    largestmug = BigIntegerField(null=True)
    cantaken = BigIntegerField(null=True)
    exttaken = BigIntegerField(null=True)
    kettaken = BigIntegerField(null=True)
    lsdtaken = BigIntegerField(null=True)
    opitaken = BigIntegerField(null=True)
    shrtaken = BigIntegerField(null=True)
    spetaken = BigIntegerField(null=True)
    pcptaken = BigIntegerField(null=True)
    xantaken = BigIntegerField(null=True)
    victaken = BigIntegerField(null=True)
    chahits = BigIntegerField(null=True)
    heahits = BigIntegerField(null=True)
    axehits = BigIntegerField(null=True)
    grehits = BigIntegerField(null=True)
    machits = BigIntegerField(null=True)
    pishits = BigIntegerField(null=True)
    rifhits = BigIntegerField(null=True)
    shohits = BigIntegerField(null=True)
    smghits = BigIntegerField(null=True)
    piehits = BigIntegerField(null=True)
    slahits = BigIntegerField(null=True)
    argtravel = BigIntegerField(null=True)
    mextravel = BigIntegerField(null=True)
    dubtravel = BigIntegerField(null=True)
    hawtravel = BigIntegerField(null=True)
    japtravel = BigIntegerField(null=True)
    lontravel = BigIntegerField(null=True)
    soutravel = BigIntegerField(null=True)
    switravel = BigIntegerField(null=True)
    chitravel = BigIntegerField(null=True)
    cantravel = BigIntegerField(null=True)
    dumpfinds = BigIntegerField(null=True)
    dumpsearches = BigIntegerField(null=True)
    itemsdumped = BigIntegerField(null=True)
    daysbeendonator = BigIntegerField(null=True)
    caytravel = BigIntegerField(null=True)
    jailed = BigIntegerField(null=True)
    hospital = BigIntegerField(null=True)
    attacksassisted = BigIntegerField(null=True)
    bloodwithdrawn = BigIntegerField(null=True)
    networth = BigIntegerField(null=True)
    missionscompleted = BigIntegerField(null=True)
    contractscompleted = BigIntegerField(null=True)
    dukecontractscompleted = BigIntegerField(null=True)
    missioncreditsearned = BigIntegerField(null=True)
    consumablesused = BigIntegerField(null=True)
    candyused = BigIntegerField(null=True)
    alcoholused = BigIntegerField(null=True)
    energydrinkused = BigIntegerField(null=True)
    nerverefills = BigIntegerField(null=True)
    unarmoredwon = BigIntegerField(null=True)
    h2hhits = BigIntegerField(null=True)
    organisedcrimes = BigIntegerField(null=True)
    territorytime = BigIntegerField(null=True)
    territoryjoins = BigIntegerField(null=True)
    arrestsmade = BigIntegerField(null=True)
    tokenrefills = BigIntegerField(null=True)
    booksread = BigIntegerField(null=True)
    traveltime = BigIntegerField(null=True)
    boostersused = BigIntegerField(null=True)
    rehabs = BigIntegerField(null=True)
    rehabcost = BigIntegerField(null=True)
    awards = BigIntegerField(null=True)
    receivedbountyvalue = BigIntegerField(null=True)
    racingskill = BigIntegerField(null=True)
    raceswon = BigIntegerField(null=True)
    racesentered = BigIntegerField(null=True)
    racingpointsearned = BigIntegerField(null=True)
    specialammoused = BigIntegerField(null=True)
    cityitemsbought = BigIntegerField(null=True)
    hollowammoused = BigIntegerField(null=True)
    tracerammoused = BigIntegerField(null=True)
    piercingammoused = BigIntegerField(null=True)
    incendiaryammoused = BigIntegerField(null=True)
    attackswonabroad = BigIntegerField(null=True)
    defendslostabroad = BigIntegerField(null=True)
    rankedwarringwins = BigIntegerField(null=True)
    retals = BigIntegerField(null=True)
    elo = BigIntegerField(null=True)
    jobpointsused = BigIntegerField(null=True)
    reviveskill = BigIntegerField(null=True)
    itemslooted = BigIntegerField(null=True)
    rankedwarhits = BigIntegerField(null=True)
    raidhits = BigIntegerField(null=True)
    territoryclears = BigIntegerField(null=True)
    refills = BigIntegerField(null=True)
